// <auto-generated />
namespace Words_learning_app_thing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_difficulty_choice_preference : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_difficulty_choice_preference));
        
        string IMigrationMetadata.Id
        {
            get { return "201901011240543_added_difficulty_choice_preference"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
