// <auto-generated />
namespace Words_learning_app_thing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_progress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_progress));
        
        string IMigrationMetadata.Id
        {
            get { return "201901011232219_added_progress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
